import { useState, useEffect } from 'react'
import { supabase } from './supabaseClient'
import { useNavigate } from 'react-router-dom'
import BottomBar from './BottomBar'

function MeusAnuncios() {
  const [user, setUser] = useState(null)
    const [anuncios, setAnuncios] = useState([])
      const [loading, setLoading] = useState(true)
        const navigate = useNavigate()

          useEffect(() => { checkUser() }, [])
            useEffect(() => { if (user) loadAnuncios() }, [user])

              const checkUser = async () => {
                  const { data: { session } } = await supabase.auth.getSession()
                      if (!session) { navigate('/'); return }
                          setUser(session.user)
                            }

                              const loadAnuncios = async () => {
                                  setLoading(true)
                                      const { data } = await supabase
                                            .from('auctions')
                                                  .select('*')
                                                        .eq('seller_id', user.id)
                                                              .eq('tipo', 'anuncio')
                                                                    .order('created_at', { ascending: false })
                                                                        if (data) setAnuncios(data)
                                                                            setLoading(false)
                                                                              }

                                                                                const handleLogout = async () => {
                                                                                    await supabase.auth.signOut()
                                                                                        navigate('/')
                                                                                          }

                                                                                            if (!user) return <div style={{ padding: '40px', textAlign: 'center' }}>Carregando...</div>

                                                                                              return (
                                                                                                  <div style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', padding: 'clamp(16px, 4vw, 40px)' }}>
                                                                                                        <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
                                                                                                                <div style={{ display: 'flex', alignItems: 'center', marginBottom: '24px', gap: '12px' }}>
                                                                                                                          <button onClick={() => navigate('/home')} style={{ background: 'white', border: 'none', padding: '10px 20px', borderRadius: '10px', fontSize: '16px', cursor: 'pointer' }}>
                                                                                                                                      Voltar
                                                                                                                                                </button>
                                                                                                                                                          <h1 style={{ color: 'white', margin: 0, fontSize: 'clamp(20px, 5vw, 32px)' }}>Meus Anúncios</h1>
                                                                                                                                                                  </div>

                                                                                                                                                                          <button onClick={() => navigate('/anuncio')} style={{ width: '100%', padding: '18px', background: '#f97316', color: 'white', border: 'none', borderRadius: '15px', fontSize: 'clamp(16px, 3vw, 22px)', fontWeight: 'bold', cursor: 'pointer', marginBottom: '24px' }}>
                                                                                                                                                                                    📢 + CRIAR NOVO ANÚNCIO
                                                                                                                                                                                            </button>

                                                                                                                                                                                                    {loading ? (
                                                                                                                                                                                                              <div style={{ textAlign: 'center', padding: '40px', color: 'white', fontSize: '20px' }}>Carregando...</div>
                                                                                                                                                                                                                      ) : anuncios.length === 0 ? (
                                                                                                                                                                                                                                <div style={{ textAlign: 'center', padding: '60px', background: 'rgba(255,255,255,0.1)', borderRadius: '15px' }}>
                                                                                                                                                                                                                                            <p style={{ color: 'white', fontSize: '20px' }}>Você ainda não criou nenhum anúncio</p>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: '20px' }}>
                                                                                                                                                                                                                                                                                    {anuncios.map(a => (
                                                                                                                                                                                                                                                                                                  <div key={a.id} onClick={() => navigate('/leilao/' + a.id)} style={{ background: 'white', borderRadius: '15px', overflow: 'hidden', cursor: 'pointer', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }}>
                                                                                                                                                                                                                                                                                                                  <img src={a.images?.[0] || ''} alt={a.title} style={{ width: '100%', height: '160px', objectFit: 'cover' }} onError={e => { e.target.style.display = 'none' }} />
                                                                                                                                                                                                                                                                                                                                  <div style={{ padding: '14px 16px' }}>
                                                                                                                                                                                                                                                                                                                                                    <h3 style={{ margin: '0 0 6px 0', fontSize: '16px', color: '#1a202c' }}>{a.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: '22px', fontWeight: 'bold', color: '#f97316' }}>
                                                                                                                                                                                                                                                                                                                                                                                          R$ {parseFloat(a.current_price || 0).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ marginTop: '8px', display: 'flex', gap: '8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={e => { e.stopPropagation(); navigate('/editar-anuncio/' + a.id) }} style={{ flex: 1, padding: '8px', background: '#667eea', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold', fontSize: '13px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Editar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <BottomBar user={user} onLogout={handleLogout} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default MeusAnuncios